version: 0.2

phases:
  install:
    runtime-versions:
      java: java8  # or 11, depending on your version
    commands:
      - echo "Installing dependencies (if any)..."
      # If you need to install any other software, do it here

  pre_build:
    commands:
      - echo "Cleaning previous builds..."
      - rm -rf build/ dist/
      - mkdir -p build/classes
      - mkdir -p dist

  build:
    commands:
      - echo "Compiling Java files..."
      - javac -d build/classes $(find src -name "*.java")
      - echo "Copying web content (if applicable)..."
      - cp -r webapp/* build/classes/
      - echo "Creating WAR file..."
      - cd build/classes
      - jar -cvf ../../dist/EcommerceApp.war *
      - cd ../../

  post_build:
    commands:
      - echo "Build completed. WAR file is in dist/EcommerceApp.war"

artifacts:
  files:
    - dist/EcommerceApp.war
