version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # or corretto11, openjdk8, etc.
    commands:
      - echo "Installing Maven..."
      - yum install -y maven

  pre_build:
    commands:
      - echo "Cleaning workspace..."
      - mvn clean

  build:
    commands:
      - echo "Building Java application..."
      - mvn package -DskipTests

  post_build:
    commands:
      - echo "Build completed. Preparing artifacts..."
      - mkdir -p build_output
      - cp target/*.jar build_output/ # For Spring Boot JARs
      # OR, for WAR-based web apps: cp target/*.war build_output/
      - cp appspec.yml build_output/
      - cp -r scripts/ build_output/scripts/ # Optional deployment scripts

artifacts:
  files:
    - build_output/**/*
